# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
canonical: http://hl7.no/fhir
name: NoDomainVitalSigns
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.no.domain.vitalsigns
status: draft
version: 0.6.2
releaseLabel: ci-build
copyrightYear: 2021+
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
dependencies:
    hl7.fhir.no.basis: 2.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  TOC: toc.html
  Download: download.html
