# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
canonical: http://hl7.no/fhir/no-domain/vitalsigns
name: NoDomainVitalSigns
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.no.domain.vitalsigns
status: draft
license: CC0-1.0
version: 0.9.0
releaseLabel: ballotNormative-2
publisher:
  name: HL7 Norway
  url: http://www.hl7.no
copyrightYear: 2024+
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
dependencies:
    hl7.fhir.no.basis: 2.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Guidance: guidance.html
  Artifacts: artifacts.html
  TOC: toc.html
  Download: download.html
